AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  team1 carl-api

  Sample SAM Template for carl-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TeamOneHelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        TeamOneSites:
          Type: Api
          Properties:
            Path: /sites
            Method: get
            RequestParameters:
              - method.request.querystring.site
        TeamOneDevices:
          Type: Api
          Properties:
            Path: /devices
            Method: get
            RequestParameters:
              - method.request.querystring.site
              - method.request.querystring.device
        TeamOneSensors:
          Type: Api
          Properties:
            Path: /sensors
            Method: get
            RequestParameters:
              - method.request.querystring.device
              - method.request.querystring.sensor
        TeamOneIngest:
          Type: Api
          Properties:
            Path: /ingest
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TeamOneHelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TeamOneHelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TeamOneHelloWorldFunction.Arn
  TeamOneHelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TeamOneHelloWorldFunctionRole.Arn
